#!/bin/sh
# Build script for Vercel deployment
# Generates env.js from Vercel environment variables

echo "// Auto-generated by build.sh — do not edit manually" > env.js
echo "window.ENV = {" >> env.js
echo "    SUPABASE_URL: '${SUPABASE_URL}'," >> env.js
echo "    SUPABASE_ANON_KEY: '${SUPABASE_ANON_KEY}'" >> env.js
echo "};" >> env.js

echo "✅ env.js generated successfully"
